In [1]:
import pandas as pd
import re
from sklearn.model_selection import train_test_split

print("Libraries imported successfully!")

Libraries imported successfully!

In [2]:
df = pd.read_csv("/mnt/g/banglafake-detection/data/processed/bangla_fake_news_500.csv")

print("Dataset loaded successfully!")
print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

df.head()

Dataset loaded successfully!
Shape: (500, 2)

Columns:
['text', 'label']

                                                text  label
0  ভারতের শাসক গোষ্ঠী বিভাজনের রাজনীতি ও বাংলাদেশ...      0
1  বারডেম জেনারেল হাসপাতালের নিবিড় পরিচর্যা কেন্দ...      1
2  ঘুমের সমস্যাটি প্রকট হয়েছে করোনা মহামারির সময় ...      0
3  জাতীয় সংসদের স্পিকারের অবর্তমানে তাঁর প্রশাসনি...      1
4  আগামী সপ্তাহেই মঙ্গোলিয়া সফর করবেন রাশিয়ার প্র...      1

In [3]:
def clean_bangla_text(text):
    if pd.isna(text):
        return ""
    
    text = str(text).strip()
    
    # English letters remove
    text = re.sub(r'[a-zA-Z]', '', text)
    
    # Extra spaces remove
    text = re.sub(r'\s+', ' ', text)
    
    # Keep only Bangla characters and spaces
    text = re.sub(r'[^\u0980-\u09FF\s]', '', text)
    
    return text.strip()


df['clean_text'] = df['text'].apply(clean_bangla_text)

print("Text cleaning completed!")
df[['text', 'clean_text']].head(10)

Text cleaning completed!

,text,clean_text
0,ভারতের শাসক গোষ্ঠী বিভাজনের রাজনীতি ও বাংলাদেশ...,ভারতের শাসক গোষ্ঠী বিভাজনের রাজনীতি ও বাংলাদেশ...
1,বারডেম জেনারেল হাসপাতালের নিবিড় পরিচর্যা কেন্দ...,বারডেম জেনারেল হাসপাতালের নিবিড় পরিচর্যা কেন্দ...
2,ঘুমের সমস্যাটি প্রকট হয়েছে করোনা মহামারির সময় ...,ঘুমের সমস্যাটি প্রকট হয়েছে করোনা মহামারির সময় ...
3,জাতীয় সংসদের স্পিকারের অবর্তমানে তাঁর প্রশাসনি...,জাতীয় সংসদের স্পিকারের অবর্তমানে তাঁর প্রশাসনি...
4,আগামী সপ্তাহেই মঙ্গোলিয়া সফর করবেন রাশিয়ার প্র...,আগামী সপ্তাহেই মঙ্গোলিয়া সফর করবেন রাশিয়ার প্র...
5,লাউ মূলত গ্রীষ্মকালীন সবজি লাউ খেলে পেট ঠান্ডা...,লাউ মূলত গ্রীষ্মকালীন সবজি লাউ খেলে পেট ঠান্ডা...
6,চট্টগ্রাম বিশ্ববিদ্যালয়ের চবি ২০২৩২৪ শিক্ষাবর্...,চট্টগ্রাম বিশ্ববিদ্যালয়ের চবি ২০২৩২৪ শিক্ষাবর্...
7,পুঁজিবাজারে তালিকাভুক্ত ব্যাংকিং খাতের প্রতিষ্...,পুঁজিবাজারে তালিকাভুক্ত ব্যাংকিং খাতের প্রতিষ্...
8,দুর্গাপূজাকে সামনে রেখে সারাদেশে সেনা মোতায়েন ...,দুর্গাপূজাকে সামনে রেখে সারাদেশে সেনা মোতায়েন ...
9,করোনা সংক্রমণের সংখ্যা দিন দিনই বাড়ছে বিশেষজ্ঞ...,করোনা সংক্রমণের সংখ্যা দিন দিনই বাড়ছে বিশেষজ্ঞ...