In [3]:
import pandas as pd
import re
import os
import numpy as np

from sklearn.model_selection import train_test_split

print("Libraries imported successfully!")

Libraries imported successfully!

In [19]:
import os

PROJECT_ROOT = "/mnt/g/banglafake-detection"

RAW_DIR = os.path.join(PROJECT_ROOT, "data", "raw")
PROCESSED_DIR = os.path.join(PROJECT_ROOT, "data", "processed")

print("Project root:", PROJECT_ROOT)
print("Raw directory:", RAW_DIR)
print("Processed directory:", PROCESSED_DIR)

Project root: /mnt/g/banglafake-detection
Raw directory: /mnt/g/banglafake-detection/data/raw
Processed directory: /mnt/g/banglafake-detection/data/processed

In [20]:
print("Project exists:", os.path.exists(PROJECT_ROOT))
print("Raw folder exists:", os.path.exists(RAW_DIR))
print("Processed folder exists:", os.path.exists(PROCESSED_DIR))

Project exists: True
Raw folder exists: True
Processed folder exists: True

In [21]:
print("Files inside raw folder:")
print("=" * 50)

for file in os.listdir(RAW_DIR):
    print(repr(file))

Files inside raw folder:
==================================================
'Bangla_Fake_News_Dataset.csv'
'Bangla_Real_News_Dataset.csv'
'English_Fake_News_Dataset.csv'
'English_Real_News_Dataset.csv'

In [22]:
real_path = os.path.join(
    RAW_DIR,
    "Bangla_Real_News_Dataset.csv"
)

fake_path = os.path.join(
    RAW_DIR,
    "Bangla_Fake_News_Dataset.csv"
)

real_df = pd.read_csv(real_path)
fake_df = pd.read_csv(fake_path)

print("Real dataset shape:", real_df.shape)
print("Fake dataset shape:", fake_df.shape)

Real dataset shape: (2000, 10)
Fake dataset shape: (2000, 10)

In [27]:
print("REAL DATASET")
display(real_df.head())

print("\nFAKE DATASET")
display(fake_df.head())

REAL DATASET

,Article ID,Domain,Date,Category,Headline,Content,Label,Source,Relation,F-Type
0,1,Prothomalo,2024-12-31 23:12:00,Sports,রোহিতের বিরুদ্ধে স্বার্থপরতার অভিযোগ সাবেক ক্র...,রোহিত শর্মাকে নিয়ে আকাশ চোপড়ার বিশ্লেষণের সারক...,1,Reporter,Related,Not Applicable
1,2,Prothomalo,2024-12-31 22:01:00,Entertainment,নতুন বছরে শিল্পকলা একাডেমির ‘তারুণ্যের উৎসব’,নতুন বছর উপলক্ষে নতুন কর্মসূচি ঘোষণা করেছে বাং...,1,Reporter,Related,Not Applicable
2,3,Prothomalo,2024-12-30 23:10:00,National,সংবিধান বাতিল করলে মুক্তিযুদ্ধ ও স্বাধীনতাকে অ...,বিএনপির জ্যেষ্ঠ যুগ্ম মহাসচিব রুহুল কবির রিজভী...,1,Reporter,Related,Not Applicable
3,4,Prothomalo,2024-12-30 22:44:00,Politics,ঢাকা বিশ্ববিদ্যালয়ে শেখ হাসিনার ‘ঘৃণাস্তম্ভে’ ...,ঢাকা বিশ্ববিদ্যালয়ের ছাত্র-শিক্ষক কেন্দ্র (টিএ...,1,Reporter,Related,Not Applicable
4,5,BBC News,2024-10-10 11:12:00,Technology,মহাকাশে সোভিয়েত প্রযুক্তি যেভাবে নাকানি চোবানি...,দ্বিতীয় বিশ্বযুদ্ধের পরপর যুক্তরাষ্ট্র এবং সোভ...,1,Reporter,Related,Not Applicable

FAKE DATASET

,Article ID,Domain,Date,Category,Headline,Content,Label,Source,Relation,F-Type
0,1,Facebook Page,2025-12-31 21:00:00,Politics,খালেদা জিয়ার মৃত্যুতে শেখ হাসিনার শোক জানানো ...,এই প্রেক্ষাপটে সামাজিক যোগাযোগমাধ্যমে বীর মুক্...,0,rumorscanner.com,Related,Fabricated
1,2,Facebook Page,2025-12-31 10:25:00,Politics,‘এবারের নির্বাচনে তারেক রহমানকে পুর্ন সমর্থন ক...,এবারের নির্বাচনে তারেক রহমানকে পুর্ন সমর্থন কর...,0,rumorscanner.com,Related,Fabricated
2,3,Facebook Page,2025-12-31 10:13:00,Politics,‘আ: লীগের চামড়া তুলে নেওয়া হবে বলতে চেয়েছিল...,গত ১১ নভেম্বর ঠাকুরগাঁওয়ে বিএনপির আলোচনা সভায...,0,rumorscanner.com,Related,Fabricated
3,4,Facebook Page,2025-12-31 10:06:00,Politics,‘আমার সাথে বেয়াদবির কারণে খালেদা হাত লুলা হয়...,বাংলাদেশ জামায়াতে ইসলামীর কেন্দ্রীয় কর্মপরিষ...,0,rumorscanner.com,Related,Fabricated
4,5,Facebook Page,2025-12-31 10:25:00,Politics,‘কমপক্ষে দুই মাসের জন্য চাঁদাবাজি বন্ধ রাখতে ন...,বাংলাদেশ জাতীয়তাবাদী দলের ভারপ্রাপ্ত চেয়ারপা...,0,rumorscanner.com,Related,Altered

In [28]:
print("Real columns:")
print(real_df.columns.tolist())

print("\nFake columns:")
print(fake_df.columns.tolist())

Real columns:
['Article ID', 'Domain', 'Date', 'Category', 'Headline', 'Content', 'Label', 'Source', 'Relation', 'F-Type']

Fake columns:
['Article ID', 'Domain', 'Date', 'Category', 'Headline', 'Content', 'Label', 'Source', 'Relation', 'F-Type']

In [29]:
print("REAL DATASET INFO")
real_df.info()

print("\n" + "=" * 60)

print("FAKE DATASET INFO")
fake_df.info()

REAL DATASET INFO
<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Article ID  2000 non-null   int64
 1   Domain      2000 non-null   str
 2   Date        2000 non-null   str
 3   Category    2000 non-null   str
 4   Headline    2000 non-null   str
 5   Content     2000 non-null   str
 6   Label       2000 non-null   int64
 7   Source      2000 non-null   str
 8   Relation    2000 non-null   str
 9   F-Type      2000 non-null   str
dtypes: int64(2), str(8)
memory usage: 11.6 MB

============================================================
FAKE DATASET INFO
<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Article ID  2000 non-null   int64
 1   Domain      2000 non-null   str
 2   Date        2000 non-null   str
 3   Category    2000 non-null   str
 4   Headline    2000 non-null   str
 5   Content     2000 non-null   str
 6   Label       2000 non-null   int64
 7   Source      2000 non-null   str
 8   Relation    2000 non-null   str
 9   F-Type      2000 non-null   str
dtypes: int64(2), str(8)
memory usage: 3.9 MB

In [30]:
print("Real dataset missing values:")
print(real_df.isnull().sum())

print("\nFake dataset missing values:")
print(fake_df.isnull().sum())

Real dataset missing values:
Article ID    0
Domain        0
Date          0
Category      0
Headline      0
Content       0
Label         0
Source        0
Relation      0
F-Type        0
dtype: int64

Fake dataset missing values:
Article ID    0
Domain        0
Date          0
Category      0
Headline      0
Content       0
Label         0
Source        0
Relation      0
F-Type        0
dtype: int64

In [31]:
print("Real dataset label distribution:")
print(real_df["Label"].value_counts())

print("\nFake dataset label distribution:")
print(fake_df["Label"].value_counts())

Real dataset label distribution:
Label
1    2000
Name: count, dtype: int64

Fake dataset label distribution:
Label
0    2000
Name: count, dtype: int64

In [32]:
df = pd.concat(
    [real_df, fake_df],
    ignore_index=True
)

print("Combined dataset shape:", df.shape)

Combined dataset shape: (4000, 10)

In [33]:
print(df["Label"].value_counts())

print("\nPercentage:")
print(
    df["Label"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

Label
1    2000
0    2000
Name: count, dtype: int64

Percentage:
Label
1    50.0
0    50.0
Name: proportion, dtype: float64

In [34]:
duplicate_count = df.duplicated(
    subset=["Content"]
).sum()

print("Duplicate content rows:", duplicate_count)

Duplicate content rows: 13

In [35]:
duplicate_rows = df[
    df.duplicated(subset=["Content"], keep=False)
].sort_values("Content")

print("Total rows involved in duplicate groups:", len(duplicate_rows))

duplicate_rows[
    ["Article ID", "Headline", "Label", "Content"]
]

Total rows involved in duplicate groups: 25

,Article ID,Headline,Label,Content
2756,757,মিয়ানমারের আরাকান আর্মি বাংলাদেশের সেন্টমার্ট...,0,মিয়ানমারের আরাকান আর্মি বাংলাদেশের সেন্টমার্...
3510,1511,আরাকান আর্মির সেন্টমার্টিন দ্বীপ দখল,0,মিয়ানমারের আরাকান আর্মি বাংলাদেশের সেন্টমার্...
2048,49,ইন্না লিল্লাহ আজ এইমাত্র গুলিবিদ্ধ সারজিস আলম,0,অন্তত ২৩ ডিসেম্বর বিকেল থেকে সামাজিক যোগাযোগ ম...
3172,1173,সারজিস আলম গুলিবিদ্ধ,0,অন্তত ২৩ ডিসেম্বর বিকেল থেকে সামাজিক যোগাযোগ ম...
2995,996,ডিরেক্টর ডা. রাজেন্দ্র বুড়ব নারকেল ফুটানো গরম...,0,আপনাদের সবাইকে বিনীত নিবেদন যে কোনও ক্যান্সার ...
3622,1623,ডা. রাজেন্দ্র বুড়বের প্রচারিত নারকেল ফুটানো গর...,0,আপনাদের সবাইকে বিনীত নিবেদন যে কোনও ক্যান্সার ...
3942,1943,নারকেল টুকরা ভিজিয়ে গরম পানি পানে ক্যান্সার কো...,0,আপনাদের সবাইকে বিনীত নিবেদন যে কোনও ক্যান্সার ...
3131,1132,দেশে থাকলেও ঢাবিতে যেতেন না’ শীর্ষক মন্তব্য কর...,0,গত ০৮ আগস্ট বিবিসি বাংলা’য় কলকাতায় আওয়ামী ল...
3261,1262,‘দেশে থাকলেও ঢাবিতে যেতেন না’ শীর্ষক মন্তব্য ক...,0,গত ০৮ আগস্ট বিবিসি বাংলা’য় কলকাতায় আওয়ামী ল...
2084,85,শেখ হাসিনার বিরুদ্ধে রায় দিতে ড. ইউনূস ২০ কোট...,0,জুলাই আন্দোলনের সময়ে সংঘটিত মানবতাবিরোধী অপরা...
3201,1202,শেখ হাসিনার বিরুদ্ধে রায় দিতে ড. ইউনূস ২০ কোট...,0,জুলাই আন্দোলনের সময়ে সংঘটিত মানবতাবিরোধী অপরা...
1086,1087,দেশে বুস্টার ডোজ পেয়েছেন প্রায় সাড়ে সাত লাখ,1,দেশে এ পর্যন্ত ৭ লাখ ৪১ হাজার ২৬৫ জনকে করোনার ...
1141,1142,দেশে বুস্টার ডোজ পেয়েছেন প্রায় সাড়ে সাত লাখ,1,দেশে এ পর্যন্ত ৭ লাখ ৪১ হাজার ২৬৫ জনকে করোনার ...
802,803,শচীনকে টপকে যে রেকর্ড গড়লেন কোহলি,1,ধসে পড়া ভারত শিবিরের হাল ধরে দেশকে জিতিয়েছেন শ...
808,809,শচীনকে টপকে যে রেকর্ড গড়লেন কোহলি,1,ধসে পড়া ভারত শিবিরের হাল ধরে দেশকে জিতিয়েছেন শ...
3427,1428,প্রধানমন্ত্রীর ত্রাণ তহবিল থেকে ওবায়দুল কাদের...,0,"প্রধানমন্ত্রীর ত্রান তহবিল লুট, কাদেরের ভ্রমণ ..."
3459,1460,প্রধানমন্ত্রীর ত্রাণ তহবিল থেকে ওবায়দুল কাদের...,0,"প্রধানমন্ত্রীর ত্রান তহবিল লুট, কাদেরের ভ্রমণ ..."
1381,1382,পাটগ্রাম সীমান্তে অনুপ্রবেশের অভিযোগে আটক বিএস...,1,লালমনিরহাটের পাটগ্রাম সীমান্তে অনুপ্রবেশের অভি...
1385,1386,পাটগ্রাম সীমান্তে অনুপ্রবেশের অভিযোগে আটক বিএস...,1,লালমনিরহাটের পাটগ্রাম সীমান্তে অনুপ্রবেশের অভি...
3381,1382,নয়া-পল্টনে হামলায় ১০৫০ জন পুলিশ সদস্যের মৃত্যু,0,১০৫০ পুলিশ হামলায় নিহত। শেখ হাসিনা সরে যাওয়া...
3557,1558,নয়া-পল্টনে হামলায় ১০৫০ জন পুলিশ সদস্যের মৃত্...,0,১০৫০ পুলিশ হামলায় নিহত। শেখ হাসিনা সরে যাওয়া...
2967,968,ড. জাকির নায়েক ওমানে গ্রেপ্তার,0,“Big breaking. জাকির নায়েক কে ওমান সরকার আজ গ...
3532,1533,ড. জাকির নায়েক ওমানে গ্রেপ্তার হন,0,“Big breaking. জাকির নায়েক কে ওমান সরকার আজ গ...
2914,915,ফিফা ক্রিশ্চিয়ানো রোনালদোকে ঘৃণা করে,0,“ফিফা ক্রিশ্চিয়ানো রোনালদোকে ঘৃণা করে৷ আমি জা...
3081,1082,ফিফা ক্রিশ্চিয়ানো রোনালদোকে ঘৃণা করে’ শীর্ষক ...,0,“ফিফা ক্রিশ্চিয়ানো রোনালদোকে ঘৃণা করে৷ আমি জা...

In [36]:
duplicate_label_check = (
    duplicate_rows
    .groupby("Content")["Label"]
    .nunique()
)

conflicting_duplicates = duplicate_label_check[
    duplicate_label_check > 1
]

print(
    "Duplicate content groups with conflicting labels:",
    len(conflicting_duplicates)
)

Duplicate content groups with conflicting labels: 0