In [3]:
import pandas as pd
import re
import os
import numpy as np

from sklearn.model_selection import train_test_split

print("Libraries imported successfully!")

Libraries imported successfully!

In [19]:
import os

PROJECT_ROOT = "/mnt/g/banglafake-detection"

RAW_DIR = os.path.join(PROJECT_ROOT, "data", "raw")
PROCESSED_DIR = os.path.join(PROJECT_ROOT, "data", "processed")

print("Project root:", PROJECT_ROOT)
print("Raw directory:", RAW_DIR)
print("Processed directory:", PROCESSED_DIR)

Project root: /mnt/g/banglafake-detection
Raw directory: /mnt/g/banglafake-detection/data/raw
Processed directory: /mnt/g/banglafake-detection/data/processed

In [20]:
print("Project exists:", os.path.exists(PROJECT_ROOT))
print("Raw folder exists:", os.path.exists(RAW_DIR))
print("Processed folder exists:", os.path.exists(PROCESSED_DIR))

Project exists: True
Raw folder exists: True
Processed folder exists: True

In [21]:
print("Files inside raw folder:")
print("=" * 50)

for file in os.listdir(RAW_DIR):
    print(repr(file))

Files inside raw folder:
==================================================
'Bangla_Fake_News_Dataset.csv'
'Bangla_Real_News_Dataset.csv'
'English_Fake_News_Dataset.csv'
'English_Real_News_Dataset.csv'

In [22]:
real_path = os.path.join(
    RAW_DIR,
    "Bangla_Real_News_Dataset.csv"
)

fake_path = os.path.join(
    RAW_DIR,
    "Bangla_Fake_News_Dataset.csv"
)

real_df = pd.read_csv(real_path)
fake_df = pd.read_csv(fake_path)

print("Real dataset shape:", real_df.shape)
print("Fake dataset shape:", fake_df.shape)

Real dataset shape: (2000, 10)
Fake dataset shape: (2000, 10)

In [27]:
print("REAL DATASET")
display(real_df.head())

print("\nFAKE DATASET")
display(fake_df.head())

REAL DATASET

,Article ID,Domain,Date,Category,Headline,Content,Label,Source,Relation,F-Type
0,1,Prothomalo,2024-12-31 23:12:00,Sports,রোহিতের বিরুদ্ধে স্বার্থপরতার অভিযোগ সাবেক ক্র...,রোহিত শর্মাকে নিয়ে আকাশ চোপড়ার বিশ্লেষণের সারক...,1,Reporter,Related,Not Applicable
1,2,Prothomalo,2024-12-31 22:01:00,Entertainment,নতুন বছরে শিল্পকলা একাডেমির ‘তারুণ্যের উৎসব’,নতুন বছর উপলক্ষে নতুন কর্মসূচি ঘোষণা করেছে বাং...,1,Reporter,Related,Not Applicable
2,3,Prothomalo,2024-12-30 23:10:00,National,সংবিধান বাতিল করলে মুক্তিযুদ্ধ ও স্বাধীনতাকে অ...,বিএনপির জ্যেষ্ঠ যুগ্ম মহাসচিব রুহুল কবির রিজভী...,1,Reporter,Related,Not Applicable
3,4,Prothomalo,2024-12-30 22:44:00,Politics,ঢাকা বিশ্ববিদ্যালয়ে শেখ হাসিনার ‘ঘৃণাস্তম্ভে’ ...,ঢাকা বিশ্ববিদ্যালয়ের ছাত্র-শিক্ষক কেন্দ্র (টিএ...,1,Reporter,Related,Not Applicable
4,5,BBC News,2024-10-10 11:12:00,Technology,মহাকাশে সোভিয়েত প্রযুক্তি যেভাবে নাকানি চোবানি...,দ্বিতীয় বিশ্বযুদ্ধের পরপর যুক্তরাষ্ট্র এবং সোভ...,1,Reporter,Related,Not Applicable

FAKE DATASET

,Article ID,Domain,Date,Category,Headline,Content,Label,Source,Relation,F-Type
0,1,Facebook Page,2025-12-31 21:00:00,Politics,খালেদা জিয়ার মৃত্যুতে শেখ হাসিনার শোক জানানো ...,এই প্রেক্ষাপটে সামাজিক যোগাযোগমাধ্যমে বীর মুক্...,0,rumorscanner.com,Related,Fabricated
1,2,Facebook Page,2025-12-31 10:25:00,Politics,‘এবারের নির্বাচনে তারেক রহমানকে পুর্ন সমর্থন ক...,এবারের নির্বাচনে তারেক রহমানকে পুর্ন সমর্থন কর...,0,rumorscanner.com,Related,Fabricated
2,3,Facebook Page,2025-12-31 10:13:00,Politics,‘আ: লীগের চামড়া তুলে নেওয়া হবে বলতে চেয়েছিল...,গত ১১ নভেম্বর ঠাকুরগাঁওয়ে বিএনপির আলোচনা সভায...,0,rumorscanner.com,Related,Fabricated
3,4,Facebook Page,2025-12-31 10:06:00,Politics,‘আমার সাথে বেয়াদবির কারণে খালেদা হাত লুলা হয়...,বাংলাদেশ জামায়াতে ইসলামীর কেন্দ্রীয় কর্মপরিষ...,0,rumorscanner.com,Related,Fabricated
4,5,Facebook Page,2025-12-31 10:25:00,Politics,‘কমপক্ষে দুই মাসের জন্য চাঁদাবাজি বন্ধ রাখতে ন...,বাংলাদেশ জাতীয়তাবাদী দলের ভারপ্রাপ্ত চেয়ারপা...,0,rumorscanner.com,Related,Altered